name: Mac Testing
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: macos-15
        steps:
            - uses: actions/checkout@v2
            # Python 3.13.1 pre-installed (https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md)
            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  pip3 install pytest
            - name: Run tests with pytest
              run: pytest
