name: Run Python Tests
on:
    push:
        branches:
            - master
    # pull_requests:
    #     branches:
    #         - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Python 3
              uses: actions/setup-python@v1
              with:
                  python-version: 3.11.10
            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  pip3 install pytest
            - name: Run tests with pytest
              run: pytest
