name: Ubuntu Testing
on:
    push:
        branches:
            - main
    # pull_requests:
    #     branches:
    #         - main

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - name: Install Python 3.12.10 (shell)
              run: |
                  export version="3.12.10"
                  curl "https://www.python.org/ftp/python/$version/Python-$version.tar.xz" -o Python-$version.tar.xz
                  tar -xJf ./Python-3.12.10.tar.xz
                  cd Python-3.12.10
                  sudo apt install build-essential checkinstall libreadline-dev libncursesw5-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libssl-dev liblzma-dev libffi-dev
                  ./configure --enable-optimizations
                  make -j$(nproc --all)
                  sudo make install
            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  python3 -m venv .venv
                  source .venv/bin/activate
                  pip3 install pytest
            - name: Run tests (using pytest)
              run: pytest
