name: Ubuntu Testing
on:
    push:
        branches:
            - main
    # pull_requests:
    #     branches:
    #         - main

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - name: Install Python 3 #3.12.3 is installed by default (https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md)
              uses: actions/setup-python@v1
              with:
                  python-version: 3.11.11
            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  pip3 install pytest
            - name: Run tests with pytest
              run: pytest
