name: Ubuntu Testing
on:
    push:
        branches:
            - main
    # pull_requests:
    #     branches:
    #         - main

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - name: Dump existing Python version
              continue-on-error: true
              run: |
                  if [[ -n $(which python3 | grep "/") ]]; then
                    which python3
                    echo "Has $(python3.12 --version) for script usage"
                  fi
                  if [[ -z $(which python3 | grep "/") ]]; then
                    echo "No version of Python currently installed."
                  fi
                  echo "Current working directory is: $(pwd)"
            - name: Install Python 3.12.10 (shell)
              run: |
                  if [[ -z $(which python3.12) ]]; then
                    export version="3.12.10"
                    export proj_name="sysdiagnose-tools"
                    curl "https://www.python.org/ftp/python/$version/Python-$version.tar.xz" -o Python-$version.tar.xz
                    tar -xJf ./Python-3.12.10.tar.xz
                    cd Python-3.12.10
                    sudo apt install build-essential checkinstall libreadline-dev libncursesw5-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libssl-dev liblzma-dev libffi-dev
                    ./configure --enable-optimizations
                    make -j$(nproc --all)
                    sudo make install
                    echo "$(which python3.12)" >> $GITHUB_PATH
                    if [[ -n $(ls ~/actions-runner/_work/$proj_name/$proj_name/ | grep "Python-$version") ]]; then
                      cd ~/actions-runner/_work/$proj_name/$proj_name
                      sudo rm -rf Python-$version Python-$version.tar.xz
                    fi
                  fi
            - name: Install pip
              run: |
                  if [[ -z $(which pip | grep "/") ]]; then
                    curl -sSL "https://bootstrap.pypa.io/get-pip.py" -o get-pip.py
                    sudo python3.12 ./get-pip.py setuptools wheel
                  fi
            - name: Install sysdiganose-tools dependencies
              run: |
                  python3.12 -m pip install --upgrade pip
                  python3.12 -m venv .venv
                  source .venv/bin/activate
                  python3.12 -m pip install pytest
            - name: Run tests (using pytest)
              run: pytest
