name: Ubuntu Testing
on:
    push:
        branches:
            - main
    # pull_requests:
    #     branches:
    #         - main

env:
    # GITHUB_PATH: "/usr/local/bin/"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games"

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - name: Dump existing Python version and current PATH
              continue-on-error: true
              run: |
                  if [[ -n $(which python3 | grep "/") ]]; then
                    which python3
                    echo "Has $(python3.12 --version) for script usage"
                  fi
                  if [[ -z $(which python3 | grep "/") ]]; then
                    echo "No version of Python currently installed."
                  fi
                  echo "Current working directory is: $(pwd)"
                  echo "Current PATH is: $PATH"
                  echo "Current git version is: $(git --version)"
            - name: Check Python 3.12 available
              id: python312available
              run: |
                  if [[ -z $(which python3.12 | grep "/") ]]; then
                    exit -1
                  fi
            - name: Install Python 3.12.10 (shell)
              if: ${{ failure() && steps.python312available.outcome == 'failure'}}
              run: |
                  export version="3.12.10"
                  export proj_name="sysdiagnose-tools"
                  curl "https://www.python.org/ftp/python/$version/Python-$version.tar.xz" -o Python-$version.tar.xz
                  tar -xJf ./Python-3.12.10.tar.xz
                  cd Python-3.12.10
                  sudo apt install build-essential checkinstall libreadline-dev libncursesw5-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libssl-dev liblzma-dev libffi-dev
                  ./configure --enable-optimizations
                  make -j$(nproc --all)
                  sudo make install
                  which python3.12
                  echo "$(which python3.12)" >> $GITHUB_PATH
                  if [[ -n $(ls ~/actions-runner/_work/$proj_name/$proj_name/ | grep "Python-$version") ]]; then
                    cd ~/actions-runner/_work/$proj_name/$proj_name
                    sudo rm -rf Python-$version Python-$version.tar.xz
                  fi
            - name: Check pip availability
              continue-on-error: true
              id: pipavailable
              run: |
                if [[ -z $(which pip | grep "/") ]]; then
                  exit -1
                fi
            - name: Install pip
              if: ${{ failure() && steps.pipavailable.outcome == 'failure' }}
              run: |
                  curl -sSL "https://bootstrap.pypa.io/get-pip.py" -o get-pip.py
                  sudo python3.12 ./get-pip.py setuptools wheel
            - name: Install dependencies and run tests
              run: |
                  echo "GitHub Path: $GITHUB_PATH"
                  python3.12 -m pip install --upgrade pip
                  python3.12 -m venv .venv
                  source .venv/bin/activate
                  python3.12 -m pip install pytest
                  pytest
